site_name: GOST
site_url: https://example.com/
repo_name: ginuerzh/gost
repo_url: https://github.com/ginuerzh/gost
edit_uri: ""

theme:
  name: material
  logo: images/gost.png
  favicon: images/favicon.ico
  # custom_dir: overrides
  features:
    - navigation.instant
    # - navigation.tabs
    # - navigation.sections
    - navigation.indexes
    - header.autohide
    # - navigation.top
  palette: 
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: teal
      accent: indigo
    - scheme: slate 
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ginuerzh/gost
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/ginuerzh/gost
    - icon: fontawesome/brands/telegram
      link: https://t.me/gogost
  alternate:
    - name: 中文
      link: /
      lang: zh
    - name: English
      link: /en/ 
      lang: en

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2015 - 2022 GOST

nav:
  - 主页: index.md
  - 入门:
    - 快速开始: getting-started/quick-start.md
    - 配置: 
      - 命令行参数: getting-started/configuration/cmd.md
      - 配置文件: getting-started/configuration/file.md
    - FAQ: /getting-started/faq.md
  - 概念:
    - 架构: concepts/architecture.md
    - 代理和转发: concepts/proxy.md
    - 转发链: concepts/chain.md
  - 组件:
    - 认证: components/auth.md
    - TLS: components/tls.md
    - 监听器(Listeners):
      - TCP: components/listeners/tcp.md
      - UDP: components/listeners/udp.md
      - TLS: components/listeners/tls.md
      - MTLS: components/listeners/mtls.md
      - WS: components/listeners/ws.md
      - MWS: components/listeners/mws.md
      - HTTP2: components/listeners/http2.md
      - H2: components/listeners/h2.md
      - QUIC: components/listeners/quic.md
      - KCP: components/listeners/kcp.md
      - SSH: components/listeners/ssh.md
      - REDU: components/listeners/redu.md
      - RTCP: components/listeners/rtcp.md
      - RUDP: components/listeners/rudp.md
      - DNS: components/listeners/dns.md
      - TUN: components/listeners/tun.md
      - TAP: components/listeners/tap.md
      - OHTTP: components/listeners/ohttp.md
      - OTLS: components/listeners/otls.md
