site_name: GOST
repo_name: go-gost/gost
repo_url: https://github.com/go-gost/gost
edit_uri: ""

theme:
  name: material
  logo: images/gost.png
  favicon: images/favicon.ico
  custom_dir: overrides
  features:
    - navigation.instant
    # - navigation.tabs
    # - navigation.sections
    - navigation.indexes
    - header.autohide
    # - navigation.top
  palette: 
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: teal
      accent: indigo
    - scheme: slate 
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/go-gost/gost
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/gogost/gost
    - icon: fontawesome/brands/telegram
      link: https://t.me/gogost
  alternate:
    - name: 中文
      link: /
      lang: zh
    - name: English
      link: /en/ 
      lang: en

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2015 - 2022 GOST

nav:
  - 主页: index.md
  - 入门:
    - 快速开始: getting-started/quick-start.md
    - 配置概述: getting-started/configuration-overview.md
    - FAQ: /getting-started/faq.md
  - 概念:
    - 架构: concepts/architecture.md
    - 代理转发和通道: concepts/proxy.md
    - 服务: concepts/service.md
    - 转发链: concepts/chain.md
    - 节点选择: concepts/selector.md
    - 分流: concepts/bypass.md
    - 域名解析: concepts/resolver.md
    - 主机映射: concepts/hosts.md
  - 教程:
    - 认证: tutorials/auth.md
    - TLS: tutorials/tls.md
    - 端口转发: tutorials/port-forwarding.md
    - Relay协议: tutorials/relay.md
    - HTTP通道: tutorials/http-tunnel.md
    - 探测防御: tutorials/probe-resistance.md
    - DNS代理: tutorials/dns.md
    - 透明代理: tutorials/redirect.md
    - TUN/TAP设备: tutorials/tuntap.md
  - 参考:
    - 配置: 
      - 命令行: reference/configuration/cmd.md
      - 配置文件: reference/configuration/file.md
    - 监听器(Listeners):
      - TCP: reference/listeners/tcp.md
      - UDP: reference/listeners/udp.md
      - TLS: reference/listeners/tls.md
      - MTLS: reference/listeners/mtls.md
      - WS: reference/listeners/ws.md
      - MWS: reference/listeners/mws.md
      - HTTP2: reference/listeners/http2.md
      - H2(C): reference/listeners/h2.md
      - PHT: reference/listeners/pht.md
      - QUIC: reference/listeners/quic.md
      - HTTP3: reference/listeners/http3.md
      - KCP: reference/listeners/kcp.md
      - SSH: reference/listeners/ssh.md
      - SSHD: reference/listeners/sshd.md
      - REDU: reference/listeners/redu.md
      - RTCP: reference/listeners/rtcp.md
      - RUDP: reference/listeners/rudp.md
      - DNS: reference/listeners/dns.md
      - TUN: reference/listeners/tun.md
      - TAP: reference/listeners/tap.md
      - OHTTP: reference/listeners/ohttp.md
      - OTLS: reference/listeners/otls.md
    - 处理器(Handlers):
      - HTTP: reference/handlers/http.md
      - SOCKS4: reference/handlers/socks4.md
      - SOCKS5: reference/handlers/socks5.md
      - Relay: reference/handlers/relay.md
      - Auto: reference/handlers/auto.md
      - HTTP2: reference/handlers/http2.md
      - SNI: reference/handlers/sni.md
      - SS: reference/handlers/ss.md
      - SSU: reference/handlers/ssu.md
      - TCP: reference/handlers/tcp.md
      - UDP: reference/handlers/udp.md
      - RTCP: reference/handlers/rtcp.md
      - RUDP: reference/handlers/rudp.md
      - SSHD: reference/handlers/sshd.md
      - DNS: reference/handlers/dns.md
      - TUN: reference/handlers/tun.md
      - TAP: reference/handlers/tap.md

