site_name: GOST博客
repo_name: go-gost/gost
repo_url: https://github.com/go-gost/gost
edit_uri: ""

theme:
  name: material
  logo: /images/gost.png
  favicon: /images/favicon.ico
  custom_dir: overrides
  features:
    - navigation.instant
    # - navigation.tabs
    # - navigation.sections
    - navigation.indexes
    - header.autohide
    - navigation.top
  palette: 
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: 白天模式
      primary: teal
      accent: indigo
    - scheme: slate 
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: 夜间模式

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/go-gost/gost
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/gogost/gost
    - icon: fontawesome/brands/telegram
      link: https://t.me/gogost

extra_css:
  - stylesheets/custom.css
  - stylesheets/homepage.css

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2015 - 2022 GOST

nav:
  - 主页: index.md
  - 2022:
    - '流量控制-分流器': 2022/bypass.md
    - 'GOST v3动态分流功能的一种实现方式': 2022/dynamic-bypass.md
  - 2017:
    - 'Linux下基于L2TP/IPSec + iptables + gost实现全局网络访问': 2017/redirect.md
  - 2016:
    - '利用gost访问内网HTTP服务': 2016/rtcp2.md
    - 'gost 2.1远程端口转发功能的使用说明': 2016/rtcp.md
    - 'gost 2.1本地端口转发功能的使用说明': 2016/tcp.md
  - 2015:
    - '利用国内vps作为中间代理转发请求到国外vps': 2015/forward.md
    - '利用letsencrypt和gost搭建https代理': 2015/lets.md
    - 'linux下利用redsocks+iptables实现全局socks5代理上网': 2015/redsocks.md
    - 'GOST的起源以及应用场景': 2015/origin.md
    - '利用PPTP, redsocks, iptables, https/socks5 proxy实现全局代理上网': 2015/redirect.md
    - 'GOST - GO Simple Tunnel': 2015/gost.md
